name: Deploy Backend

on:
  push:
    branches:
      - infra-scaleway-v1
    paths:
      - 'backend/**'

env:
  REGISTRY: rg.fr-par.scw.cloud
  NAMESPACE: portfolio-sv-registry
  IMAGE_NAME: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Scaleway Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Install Scaleway CLI
        run: |
          curl -s https://raw.githubusercontent.com/scaleway/scaleway-cli/master/scripts/get.sh | sh

      - name: Deploy to Scaleway Serverless Container
        run: |
          scw container container update \
            ${{ secrets.SCW_ACCESS_KEY }} \
            secret-key=${{ secrets.SCW_SECRET_KEY }} \
            project-id=${{ secrets.SCW_PROJECT_ID }} \
            region=fr-par \
            container-id=7b4f8a8d-8bae-41f6-bef0-94131c681e6e \
            redeploy=true